services:
    sonata.block.exception.filter.debug_only:
        class: Sonata\BlockBundle\Exception\Filter\DebugOnlyFilter
        arguments: ["%kernel.debug%"]
        public: true
    sonata.block.exception.renderer.throw:
        class: Sonata\BlockBundle\Exception\Renderer\MonkeyThrowRenderer
        public: true

    admin.category:
        class: App\Admin\CategoryAdmin
        arguments: [~, App\Entity\Category, ~]
        tags:
            - { name: sonata.admin, group: Catalog, manager_type: orm, label: Категории }
        public: true



    admin.product:
        class: App\Admin\ProductAdmin
        arguments: [~, App\Entity\Product, ~]
        tags:
            - { name: sonata.admin, group: Catalog, manager_type: orm, label: Товары }
        public: true

    admin.orders:
        class: App\Admin\OrdersAdmin
        arguments: [~, App\Entity\Order, ~]
        tags:
            - { name: sonata.admin, group: Catalog, manager_type: orm, label: Товары }
        public: true
